// Shared loader for the combined node-worker.wasm bundle (llhttp + zlib).
// Consumers (`internal-binding/http_parser`, `internal-binding/zlib`) register
// their env imports at module-load time via `registerEnv`, then call
// `getExports()` lazily on first use. Wasm instantiation happens once.

// @ts-ignore — generated by prepare-node.js, lives outside the TS rootDir
import nodeWorkerWasmBase64 from "../../../node_core/wasm-build/node-worker.wasm.js";

// Subset of the exports we actually use from JS. Loose-typed because the wasm
// instance returns Function-shaped values; consumers cast at the call site.
export interface NodeWorkerWasmExports {
	memory: WebAssembly.Memory;
	malloc(size: number): number;
	free(ptr: number): void;

	// llhttp shim
	llhttp_wasm_alloc(type: number): number;
	llhttp_wasm_free(ptr: number): void;
	llhttp_wasm_init(ptr: number, type: number): void;
	llhttp_wasm_smoke_test(): number;
	llhttp_execute(ptr: number, data: number, len: number): number;
	llhttp_finish(ptr: number): number;
	llhttp_pause(ptr: number): void;
	llhttp_resume(ptr: number): void;
	llhttp_resume_after_upgrade(ptr: number): void;
	llhttp_get_type(ptr: number): number;
	llhttp_get_http_major(ptr: number): number;
	llhttp_get_http_minor(ptr: number): number;
	llhttp_get_method(ptr: number): number;
	llhttp_get_status_code(ptr: number): number;
	llhttp_get_upgrade(ptr: number): number;
	llhttp_reset(ptr: number): void;
	llhttp_should_keep_alive(ptr: number): number;
	llhttp_get_errno(ptr: number): number;
	llhttp_get_error_reason(ptr: number): number;
	llhttp_get_error_pos(ptr: number): number;
	llhttp_errno_name(err: number): number;
	llhttp_set_lenient_headers(ptr: number, val: number): void;
	llhttp_set_lenient_chunked_length(ptr: number, val: number): void;
	llhttp_set_lenient_keep_alive(ptr: number, val: number): void;
	llhttp_set_lenient_transfer_encoding(ptr: number, val: number): void;
	llhttp_set_lenient_version(ptr: number, val: number): void;
	llhttp_set_lenient_data_after_close(ptr: number, val: number): void;
	llhttp_set_lenient_optional_lf_after_cr(ptr: number, val: number): void;
	llhttp_set_lenient_optional_crlf_after_chunk(ptr: number, val: number): void;
	llhttp_set_lenient_optional_cr_before_lf(ptr: number, val: number): void;
	llhttp_set_lenient_spaces_after_chunk_size(ptr: number, val: number): void;

	// zlib shim
	zlib_alloc(mode: number): number;
	zlib_init(
		h: number,
		windowBits: number,
		level: number,
		memLevel: number,
		strategy: number,
		dictPtr: number,
		dictLen: number
	): number;
	zlib_ensure_in_buf(h: number, size: number): number;
	zlib_ensure_out_buf(h: number, size: number): number;
	zlib_write(h: number, flush: number, inLen: number, outLen: number): number;
	zlib_avail_in(h: number): number;
	zlib_avail_out(h: number): number;
	zlib_get_err(h: number): number;
	zlib_get_msg(h: number): number;
	zlib_params(h: number, level: number, strategy: number): number;
	zlib_reset(h: number): number;
	zlib_end(h: number): void;
	zlib_crc32_buf(ptr: number, len: number, initial: number): number;
	zlib_smoke_test(): number;

	// brotli shim
	brotli_alloc(mode: number): number;
	brotli_init(
		h: number,
		paramsPtr: number,
		paramsLen: number,
		dictPtr: number,
		dictLen: number
	): number;
	brotli_ensure_in_buf(h: number, size: number): number;
	brotli_ensure_out_buf(h: number, size: number): number;
	brotli_write(h: number, op: number, inLen: number, outLen: number): number;
	brotli_avail_in(h: number): number;
	brotli_avail_out(h: number): number;
	brotli_get_err(h: number): number;
	brotli_get_msg(h: number): number;
	brotli_end(h: number): void;
}

type EnvImports = Record<string, (...args: any[]) => any>;

// Always-provided env imports. `emscripten_notify_memory_growth` is emitted
// because we build with `-sALLOW_MEMORY_GROWTH=1`; JS-side callers re-fetch
// memory views on every wasm call already, so the notification is a no-op.
const envImports: EnvImports = {
	emscripten_notify_memory_growth(_index: number) {},
};
let wasmExports: NodeWorkerWasmExports | null = null;

function decodeBase64(base64: string): Uint8Array {
	if (typeof atob === "function") {
		return Uint8Array.from(atob(base64), (char) => char.charCodeAt(0));
	}
	if (typeof Buffer !== "undefined") {
		return Uint8Array.from(Buffer.from(base64, "base64"));
	}
	throw new Error("No base64 decoder available for node-worker wasm");
}

export function registerEnv(callbacks: EnvImports): void {
	Object.assign(envImports, callbacks);
}

export function getExports(): NodeWorkerWasmExports {
	if (wasmExports) return wasmExports;

	const module = new WebAssembly.Module(decodeBase64(nodeWorkerWasmBase64));
	const instance = new WebAssembly.Instance(module, {
		// libc pulls in a handful of wasi stubs through paths like abort() ->
		// __wasi_proc_exit and __stdio_write -> fd_write. None should fire in
		// steady-state, but the import has to resolve to a callable so wasm
		// instantiation doesn't fail.
		wasi_snapshot_preview1: {
			proc_exit(code: number) {
				throw new Error(
					`Unexpected wasi proc_exit(${code}) from node-worker wasm`
				);
			},
			fd_write(
				fd: number,
				iovsPtr: number,
				iovsLen: number,
				nwrittenPtr: number
			): number {
				// Sum iov lengths so libc sees "all bytes written" and doesn't
				// loop retrying. Optionally surface the bytes to console so a
				// rogue assert/abort message isn't silently swallowed.
				if (!wasmExports) return 0;
				const mem = wasmExports.memory.buffer;
				const view = new DataView(mem);
				let total = 0;
				const chunks: Uint8Array[] = [];
				for (let i = 0; i < iovsLen; i++) {
					const base = view.getUint32(iovsPtr + i * 8, true);
					const len = view.getUint32(iovsPtr + i * 8 + 4, true);
					if (len) chunks.push(new Uint8Array(mem, base, len));
					total += len;
				}
				view.setUint32(nwrittenPtr, total, true);
				if (chunks.length) {
					const joined = new Uint8Array(total);
					let off = 0;
					for (const c of chunks) {
						joined.set(c, off);
						off += c.byteLength;
					}
					const text = new TextDecoder().decode(joined);
					// fd 1 = stdout, fd 2 = stderr; route appropriately.
					(fd === 2 ? console.error : console.log)(
						`[node-worker wasm fd ${fd}] ${text.replace(/\n$/, "")}`
					);
				}
				return 0;
			},
			fd_close(_fd: number): number {
				return 0;
			},
			fd_seek(
				_fd: number,
				_offset: bigint,
				_whence: number,
				_newoffsetPtr: number
			): number {
				return 0;
			},
		},
		env: envImports,
	});

	wasmExports = instance.exports as unknown as NodeWorkerWasmExports;
	return wasmExports;
}
